/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Editorial Engineering 视觉令牌 - CSS 变量形式
        "surface": "var(--color-surface)",
        "background": "var(--color-background)",
        "primary": "var(--color-primary)",
        "secondary": "var(--color-secondary)",
        "text-muted": "var(--color-text-muted)",
        "border-subtle": "var(--color-border-subtle)",
        "glow-cyan": "var(--color-glow-cyan)",
        "glow-indigo": "var(--color-glow-indigo)",
        "surface-card": "var(--color-surface-card)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-container": "var(--color-surface-container)",
        "outline": "var(--color-outline)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "outline-variant": "var(--color-outline-variant)",
        "error": "var(--color-error)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "primary-container": "var(--color-primary-container)",
        "error-container": "var(--color-error-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-error": "var(--color-on-error)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-background": "var(--color-on-background)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-error-container": "var(--color-on-error-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "tertiary": "var(--color-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "container-max": "1200px",
        "lg": "48px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px",
        "sm": "12px",
        "md": "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", { "lineHeight": "1.15", "letterSpacing": "0", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.05", "letterSpacing": "0", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.75", "fontWeight": "400" }],
        "label-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}