/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Editorial Engineering 视觉令牌
        "surface": "#161514",
        "background": "#0d0d0c",
        "primary": "#8addec",
        "secondary": "#d8b978",
        "text-muted": "#a9a29b",
        "border-subtle": "rgba(255, 255, 255, 0.1)",
        "glow-cyan": "rgba(34, 211, 238, 0.15)",
        "glow-indigo": "rgba(99, 102, 241, 0.15)",
        "surface-card": "#1c1b19",
        "tertiary-fixed-dim": "#ffb957",
        "on-primary-container": "#005763",
        "inverse-on-surface": "#313030",
        "surface-container": "#24221f",
        "outline": "#859397",
        "on-primary": "#00363e",
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#3c494c",
        "error": "#ffb4ab",
        "secondary-fixed": "#e1e0ff",
        "on-secondary": "#1000a9",
        "surface-variant": "#34312d",
        "surface-bright": "#3b3833",
        "on-secondary-fixed-variant": "#2f2ebe",
        "secondary-container": "#3131c0",
        "on-secondary-container": "#b0b2ff",
        "primary-container": "#22d3ee",
        "error-container": "#93000a",
        "on-secondary-fixed": "#07006c",
        "on-error": "#690005",
        "primary-fixed-dim": "#2fd9f4",
        "on-primary-fixed": "#001f25",
        "on-surface": "#f1ece6",
        "primary-fixed": "#a2eeff",
        "on-background": "#f1ece6",
        "surface-tint": "#2fd9f4",
        "on-tertiary-container": "#6e4600",
        "tertiary-fixed": "#ffddb5",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary": "#462b00",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006877",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#c9c1b8",
        "surface-dim": "#131313",
        "tertiary-container": "#ffb13b",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary": "#ffd6a3",
        "on-primary-fixed-variant": "#004e5a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "container-max": "1200px",
        "lg": "48px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px",
        "sm": "12px",
        "md": "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", { "lineHeight": "1.15", "letterSpacing": "0", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.05", "letterSpacing": "0", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.75", "fontWeight": "400" }],
        "label-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
